Oauth authentication
st-selukov/serg pull request #10
Opened 2017-07-09 21:56 UTC by st-selukov

2017-07-09 21:59 UTC, st-selukov commented on app/models/user.rb
>  end
Запутался( Получается , что пользователь аутентифицирующийся впервые через твиттер,  вводит свой email,   письмо для подтверждения не отправляется, а вот если опять вхожу им, опять запрашиваю email , письмо отправляется,  но пользователь уже активирован

2017-07-10 07:45 UTC, vkurennov commented on app/models/user.rb
>  end
Нужно принудитлеьно отправить ему письмо и сделать аккаунт не подтвержденным в первый раз. Для этого у devise есть методы send_confirmation_instructions! (у модели User), также можно email установить в поле unconfirmed_email, и тогда он автоматом станет неподтвержденным.

2017-07-11 07:34 UTC, vkurennov requested changes

2017-07-11 07:34 UTC, vkurennov commented on app/models/user.rb
> +      user.send_confirmation_instructions
А зачем снова отправлять инструкции, если у тебя это только что созданный юзер, и он по-умолчанию не подтвержден? Соответсвенно, при создании ему и так будут отправлены инструкции

2017-07-11 07:34 UTC, vkurennov commented on app/models/user.rb
> +    user = User.where(email: email).first
А если на предудущем шаге условие не выполнилось и email пустой?

2017-07-11 07:34 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +  def user_with_auth
Это точно надо в отдельный метод выносить?

2017-07-11 07:34 UTC, vkurennov commented on app/views/omniauth_callbacks/confirm_email.html.slim
> +    = hidden_field_tag 'auth[provider]', auth.provider
Очень плохо светить данные, полученные от провайдера в форме, пусть и в скрытых полях. Используй сессию для хранения этих данных

2017-07-11 07:34 UTC, vkurennov commented on spec/acceptance/users_specs/sign_in_with_oauth_spec.rb
> +  scenario 'sign in with  provider twitter,  provider does not give the email ' do
Тут несколько сценариев: юзер вводит email, которого еще нет в системе и юзер вводит email, который уже есть в системе.

2017-07-12 06:51 UTC, vkurennov approved these changes

2017-07-12 06:51 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +      session[:provider] = @auth.provider
Используй ключи, начинающиеся с 'devise.', чтобы после логина автоматом очистить эти значения (а их надо чистить, когда они уже не нужны). Например, 'devise.oauth_provider'

2017-07-12 21:24 UTC, closed without merging