Added authentication with Devise and removal of questions and answers
st-selukov/serg pull request #3
Opened 2017-05-27 00:04 UTC by st-selukov

2017-05-27 09:20 UTC, vkurennov requested changes

2017-05-27 09:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
1. Лучше проверять по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2017-05-27 09:20 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
Далеко не во всех контроллерах это будет нужно, поэтому не стоит включать этот фильтр глобально.

2017-05-27 09:20 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Замени на вызов `User#author_of?`

2017-05-27 09:20 UTC, vkurennov commented on app/views/questions/index.html.slim
> +            -if user_signed_in? && question.user == current_user
Замени на вызов `User#author_of?`

2017-05-27 09:20 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      -if user_signed_in? && @question.user == current_user
Замени на вызов `User#author_of?`

2017-05-27 09:20 UTC, vkurennov commented on app/views/questions/show.html.slim
> +          -if user_signed_in? && answer.user == current_user
Замени на вызов `User#author_of?`

2017-05-27 09:20 UTC, vkurennov commented on app/views/questions/_form.html.slim
> += form_for @question, class: 'ask-question-form' do |f|
Тут должен быть вывод ошибок валидации

2017-05-27 09:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to root_url
Нельзя делать редирект, если есть ошибки. Так потеряется все, что ввел юзер и сами ошибки валидации вывести будет нельзя

2017-05-27 09:20 UTC, vkurennov commented on spec/acceptance/answers_specs/user_can_create_answer_spec.rb
> +    expect(page).to_not have_css '.single-question-answers__current_answer'
Нужно проверить, что система вывела ошибки валидации. На верстку и css полагаться не стоит, важно не какая верстка, а то, что видит пользователь

2017-05-27 09:20 UTC, vkurennov commented on spec/acceptance/questions_specs/user_can_create_question_spec.rb
> +  scenario 'authenticated user try created question' do
Нужен сценарий с невалидной формой - проверить, что выводятся ошибки валидации

2017-05-27 09:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect {post :create, params: {question_id: question.id, answer: attributes_for(:answer)}}
Нужен тест на связь овтета с залогиненным юзером

2017-05-27 09:20 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>        it 'try save new question in database' do
Нужно проверить связь с залогиненным юзером

2017-05-28 23:27 UTC, st-selukov commented on app/views/answers/_form.html.slim
> +  = render 'commons/errors', resource: @answer
Виталий я тут запутался, не пойму  почему вывод ошибок валидации не работает

2017-05-29 09:05 UTC, vkurennov requested changes

2017-05-29 09:05 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer)
А что будет, если условие не выполнилось? Рельсы попытсюатся отрендерить вид destroy, не найдут его и будет исключение, юзер увидит 500-ю ошибку. Не очень хорошо...

2017-05-29 09:05 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author_of?(@question)
И снова: что будет, если условие не выполнится?

2017-05-29 09:05 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      redirect_to question_path(@question)
У тебя при редиректе будут терятсья ошибки валидации. Тут нужен рендер страницы с формой

2017-05-29 09:05 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +  = render 'commons/errors', resource: @answer
Потому что в контроллере ты делаешь безусловный редирект при создании ответа. А редирект - это новый запрос и твой невалидный ответ исчезает вместе со всеми ошибками валидации и тем, что ввел юзер. 
Ну и выводить ошибки после формы как-то не логично, обычно до формы выводят.

2017-05-29 09:05 UTC, vkurennov commented on app/views/questions/_form.html.slim
> +  = render 'commons/errors', resource: @question
лучше в начале формы выводить

2017-05-29 09:05 UTC, vkurennov commented on spec/acceptance/answers_specs/user_can_create_answer_spec.rb
> +    expect(page).to_not have_css '.single-question-answers__current_answer'
Не исправлено. И,кстати, если тест все же проходит, а ошибки, как мы выяснили, не выводятся, то толку от такого теста ноль, он бесполезен.

2017-05-29 09:05 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'фnswer belongs to the user' do
опечатка

2017-05-29 09:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to be true
Можно писать так: `expect(user).to be_author_of(question)`

2017-05-29 09:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(answer)).to be true
метод универсальный, работает с любым объектом, у которого есть user_id, поэтому не надо проверять на каждом типе аргумента, достаточно на одном

2017-05-30 08:55 UTC, vkurennov approved these changes

2017-05-30 08:55 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author_of?(@question)
Не исправлено

2017-05-30 13:37 UTC, merged