vote for  answer via ajax
st-selukov/serg pull request #7
Opened 2017-06-17 12:58 UTC by st-selukov

2017-06-18 11:21 UTC, st-selukov commented on spec/shared_examples/controller_voted.rb
> +
Виталий, подскажи пожалуйста, почему тест может не   проходить ?

2017-06-18 11:38 UTC, vkurennov commented on spec/shared_examples/controller_voted.rb
> +      put :vote_up, params: { id: parent.id, format: :js}
А почему запрос в формате js? У тебя же json должен быть

2017-06-19 10:58 UTC, vkurennov requested changes

2017-06-19 10:58 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $('.vote-up-answer-link').on('click').bind 'ajax:success', (e) ->
не нужен `on('click')`, лучше` $('.vote-up-answer-link').on('ajax:success')`

2017-06-19 10:58 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +    answer = $.parseJSON(e.detail[2].responseText)
в e.detail[1] (или 0, не помню точно) приходит уже распарсенный json, поэтому его можно не парсить

2017-06-19 10:58 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $('.vote-down-answer-link').on('click').bind 'ajax:success', (e) ->
Полное дублирование предыдущего обработчика. Можно повесить один обработчик на 2 селектора сразу

2017-06-19 10:58 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $('.vote-reset-answer-link').on('click').bind 'ajax:success', (e) ->
Опять дублирование

2017-06-19 10:58 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $('.vote-up-question-link').on('click').bind 'ajax:success', (e) ->
Здесь дублирование между 3-мя обработчикми и между обработчиками для ответов, а ведь можно сами селекторы назвать универсально, а тип и id объекта получить из json, который приходит.

2017-06-19 10:58 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      @parent.user.change_reputation(YOUR_VOTABLE_IS_VOTED_UP)
Слишком много логики в контроллере, все эти действия должны быть в методах модели vote_up/vote_down. Потому что если мы как-то по-другому будем вызывать методы голосования, например, через API, то нам придется дублировать весь этот код. Именно поэтому всю логику нужно держать в методах модели, тогда все будет работать как надо вне зависимости от того, откуда мы вызывали метод голосования

2017-06-19 10:58 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    if user_signed_in? && !current_user.votable_owner?(@parent)
1. Чтобы не проверять каждый раз на `user_signed_in?` нужно включить фильтры `authenticate_user!` для этих экшенов.
2. Что будет, если одно из этих условий не выполнится?

2017-06-19 10:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      current_user.change_reputation(YOU_PLACED_QUESTION_OR_ANSWER)
Такие вещи надо делать через коллбеки контроллеров, чтобы они не зависели от того, как именно был создан объект

2017-06-19 10:58 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes_sum > 0 ? update(votes_sum: votes_sum - 1) : update(votes_sum: votes_sum + 1)
Такие "ручные" вещи всегда опасны, потому что где-то может оказаться баг в логике. Поэтому лучше пересчитывать сумму принудительно, используя метод sum. Для этого нужно будет хранить само значение голоса в базе

2017-06-19 10:58 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    vote.destroy
Если голос удалить напрямую, вызвав destroy, а не этот метод, то сумма не пересчитается. Это может вести к багам. Лучше пересчет суммы (и для создания голосов тоже) повестить на коллбеки в модель Vote.

2017-06-19 10:58 UTC, vkurennov commented on app/models/user.rb
> +  def votable_owner?(votable)
Чем этот метод отличается от `author_of?` Это дублирование. Если хочется, чтобы метод назывался по-другому, используй alias и задай еще одно имя методу

2017-06-19 10:58 UTC, vkurennov commented on app/models/user.rb
> +    id == votable.user.id
Нет смысла так сравнивать по id, потому что ты все равно грузишь ассоциацию user из базы в память. Весь смысл сравнивать по id как раз в том, чтобы не грузить ассоциацию

2017-06-19 10:58 UTC, vkurennov commented on app/models/vote.rb
> +  validates :user_id, :votable_id, :votable_type, presence: true
Не нужно валидировать поля ассоциаций belongs_to, это рельсы делают автоматически. Также не имеет смысла валидировать votable_id и votable_type, потому что они устанавливаются после валидаци.

2017-06-19 10:58 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      votes.create(user: voter)
Тут хорошо бы хранить и значение голоса, чтобы знать как именно проголосовал каждый пользователь

2017-06-19 10:58 UTC, vkurennov commented on app/models/vote.rb
> +  validates :user_id, :votable_id, :votable_type, presence: true
А вот значение голоса хорошо бы проверить на допустимые значения

2017-06-19 10:58 UTC, vkurennov commented on app/views/answers/_vote.html.slim
> += link_to vote_up_answer_path(answer) , remote: true,  data: { answer_id: answer.id },
А нужен ли здесь и в других ссылках data-атрибут с id ответа?

2017-06-19 10:58 UTC, vkurennov commented on app/views/questions/_vote.html.slim
> += link_to vote_up_question_path(question) , remote: true,  data: { question_id: question.id },
Попробуй сделать универсальный паршл для голосоавния. Для этого классы нужно назвать универсально, отказаться от data-атрибута и применить [polymorphic_path](http://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html).

2017-06-20 13:23 UTC, st-selukov commented on app/models/vote.rb
> +  after_save :change_vote_sum, :up_owner_reputation, :change_votable_user_reputation
Виталий я здесь запутался, коллбеки  правильно не работают.

2017-06-20 14:46 UTC, vkurennov requested changes

2017-06-20 14:46 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +    votes_handler("answer", e)
И вновь дублирование, код одинаковый, только селекторы разные. Тут нужно на все селекторы повесить один обработчик. И если сделать названия классов селекторов универсальными, то не придется передавать эти "answer" и "question"

2017-06-20 14:46 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  votable_id = event.detail[0].id
елси в json передвать не только id, но и тип, то можно из самого ответа понять вопрос это или ответ и составить нужный селектор

2017-06-20 14:46 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    user.change_reputation(YOUR_VOTABLE_IS_VOTED_UP)
Почему всегда VOTED_UP? А если был голос против?

2017-06-20 14:46 UTC, vkurennov commented on app/models/vote.rb
> +  after_save :change_vote_sum, :up_owner_reputation, :change_votable_user_reputation
Как должно быть правильно и как они работают в реальности? Что не так?

2017-06-20 14:46 UTC, vkurennov commented on app/models/vote.rb
> +    votable.update_votes
Т.к. ассоциация votable отмечена как optional, то votable может и не быть, тут нужно условие добавить

2017-06-20 18:23 UTC, st-selukov commented on app/models/vote.rb
> +  after_save :change_vote_sum, :up_owner_reputation, :change_votable_user_reputation
Когда  При создании голоса , когда вызывается
change_votable_user_reputation
по идее я изменяю у   хозяина вопроса или ответа репутацию на 5, но  число увеличивается  на 10

2017-06-20 18:24 UTC, st-selukov commented on app/models/vote.rb
> +  after_save :change_vote_sum, :up_owner_reputation, :change_votable_user_reputation
При создании голоса , когда вызывается
change_votable_user_reputation
по идее я изменяю у   хозяина вопроса или ответа репутацию на 5, но  число увеличивается  на 10

2017-06-20 19:19 UTC, st-selukov commented on app/controllers/concerns/voted.rb
> +      render json: 'У вас не хватает репутации для этого', status: :unprocesable_entity
Виталий, подскажи здесь пожалуйста, как мне лучше обработать эту ситуацию. Вызываю коллбек перед  экшенами, для проверки репутации , если ее не хватает, соответственно голосовать нельзя. Запутался(

2017-06-21 10:20 UTC, vkurennov commented on app/models/vote.rb
> +  after_save :change_vote_sum, :up_owner_reputation, :change_votable_user_reputation
Но ведь ты же еще делаешь апдейт репутации в методе консерна Votable#up_owner_reputation, как раз не те же самые 5. Вот 5+5  и дает 10.

2017-06-21 10:21 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      render json: 'У вас не хватает репутации для этого', status: :unprocesable_entity
Не совсем понял вопроса. Возвращай тут статуст :forbidden лучше, а на клиенте обработчик на ajax:error

2017-06-21 18:09 UTC, vkurennov approved these changes

2017-06-21 18:09 UTC, vkurennov commented on app/assets/javascripts/votes.coffee
> +  $('.vote-down-link').on 'ajax:success', (e) ->
Ну так опять дублирования, у тебя же обработчики один в один, повесь их сразу на 2 селектора:

`$('.vote-up-link, .vote-down-link').on ...`

2017-06-21 18:27 UTC, merged