Added comment creation and functionality pub/sub via ActionCable
st-selukov/serg pull request #8
Opened 2017-06-27 09:20 UTC by st-selukov

2017-06-27 09:27 UTC, st-selukov commented on app/assets/javascripts/templates/answer.jst.skim
> +        ==JST["templates/attachment"]({obj: @[2][0], user_id: @[1].id})
Я не  разобрался как в этих шаблонах делать циклы, поэтому не смог вывести все аттачменты (

2017-06-27 13:24 UTC, vkurennov requested changes

2017-06-27 13:24 UTC, vkurennov commented on app/assets/javascripts/channels/answers.coffee
> +    connected: ->
Если нет обработчиков, зачем писать пустые функции?

2017-06-27 13:24 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +        ==JST["templates/attachment"]({obj: @[2][0], user_id: @[1].id})
Здесь можно использовать обычный js (for) или, например each из jquery

2017-06-27 13:24 UTC, vkurennov commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
У тебя один канала на все ответы, без разделения по вопросам. Это может создавать слишком большую нагрузку на канал и приложение начнет тормозить в браузере пользователя. Нужно слать ответы только для того вопроса, который открыт у юзера (т.е. по текущему user_id)

2017-06-27 13:24 UTC, vkurennov commented on app/channels/answers_channel.rb
> +  def unsubscribed
Зачем тут пустой метод?

2017-06-27 13:24 UTC, vkurennov commented on app/channels/comments_channel.rb
> +class CommentsChannel < ApplicationCable::Channel
Тут те же проблемы, что и в AnswersChannel

2017-06-27 13:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    ActionCable.server.broadcast('answers', [@answer, @answer.user, @answer.attachments])
Почему передаешь массив, а не хеш? хеш ведь как json придет, т.е. структуриованный объект. Тогда и код в skim-шаблонах будет более читаем, т.к. изабавишься от этих индексов и будешь обращаться по имени к атрибутам объекта

2017-06-28 22:05 UTC, st-selukov commented on app/assets/javascripts/templates/answer.jst.skim
> +      img src="/assets/default-avatar.png" alt="Default avatar"
Виталий такой вопрос у меня.Так как в скиме не могу использовать  рельсовые хелперы,  а при деплое после компиляции ассетов  url картинки  поменяется и соответственно картинка не отобразится. Как  тут можно лучше решить эту проблему ?

2017-06-29 08:37 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +      img src="/assets/default-avatar.png" alt="Default avatar"
2 варианта:

- если картинка статичная, можно положить ее в public/ и тогда она будет доступна от корня проекта, т.е. просто /default-avatar.png
- если картинка динамическая, например, аватар, загруженный юзером, то тогда надо путь (или хотя бы имя) к ней передавать с сервера в самом json ответе.

2017-06-29 08:38 UTC, vkurennov approved these changes

2017-06-29 10:52 UTC, merged